/**
 * Centralized Agent Authorization Middleware
 *
 * This middleware receives a trusted AgentIdentity generated
 * by agent-identity.ts and decides whether a protected action
 * should be:
 *
 * - ALLOW
 * - DENY
 * - REQUIRE_APPROVAL
 *
 * Security goals:
 *
 * 1. Every protected action has a trusted identity:
 *    userId
 *    agentId
 *    role
 *    workspaceId
 *    runId
 *
 * 2. Role-based authorization is enforced before runtime.
 *
 * 3. Agents cannot access resources outside their workspace.
 *
 * 4. Sensitive system resources are always denied.
 *
 * 5. High-risk operations may require human approval.
 *
 * 6. Every authorization decision is recorded in the audit log.
 */

import * as path from "node:path";

import type {
  AgentIdentity,
  AgentRole,
} from "./agent-identity.js";


/* =========================================================
 * 1. Authorization Types
 * ======================================================= */

export type AuthorizationDecision =
  | "ALLOW"
  | "DENY"
  | "REQUIRE_APPROVAL";


export type ProtectedAction =
  | "FILE_READ"
  | "FILE_WRITE"
  | "SHELL_EXECUTE"
  | "TOOL_INVOKE"
  | "NETWORK_REQUEST"
  | "SECRET_READ";


export type RiskLevel =
  | "LOW"
  | "MEDIUM"
  | "HIGH";


/* =========================================================
 * 2. Protected Resource
 * ======================================================= */

export interface ProtectedResource {

  /**
   * File or resource path.
   *
   * Examples:
   *
   * result.txt
   * /workspace/agent-001/result.txt
   * /etc/shadow
   */
  path?: string;


  /**
   * Tool name.
   *
   * Examples:
   *
   * bash
   * file_write
   * database_query
   */
  tool?: string;


  /**
   * Risk classification.
   */
  risk?: RiskLevel;


  /**
   * Human approval reference.
   */
  approvalId?: string;
}


/* =========================================================
 * 3. Authorization Request
 * ======================================================= */

/**
 * Identity is NOT supplied directly by the Agent.
 *
 * It must be generated by:
 *
 * resolveAgentIdentity(...)
 *
 * in agent-identity.ts.
 */
export interface AuthorizationRequest {

  /**
   * Trusted identity.
   */
  identity: AgentIdentity;


  /**
   * Requested protected operation.
   */
  action: ProtectedAction;


  /**
   * Target resource.
   */
  resource: ProtectedResource;
}


/* =========================================================
 * 4. Authorization Result
 * ======================================================= */

export interface AuthorizationResult {

  decision: AuthorizationDecision;

  reason: string;

  userId: string;

  agentId: string;

  role: AgentRole;

  workspaceId: string;

  runId: string;

  action: ProtectedAction;

  resource: ProtectedResource;

  timestamp: string;
}


/* =========================================================
 * 5. Audit Log
 * ======================================================= */

export interface AuditLogEntry
  extends AuthorizationResult {}


/* =========================================================
 * 6. Authorization Dependencies
 * ======================================================= */

export interface AuthorizationDependencies {

  /**
   * Resolve a trusted workspace ID into an absolute path.
   */
  resolveWorkspaceRoot(
    workspaceId: string
  ): Promise<string>;


  /**
   * Persist every authorization decision.
   */
  writeAuditLog(
    entry: AuditLogEntry
  ): Promise<void>;


  /**
   * Optional human approval verification.
   */
  isApprovalGranted?(
    approvalId: string,
    request: AuthorizationRequest
  ): Promise<boolean>;
}


/* =========================================================
 * 7. Sensitive System Paths
 * ======================================================= */

const SENSITIVE_SYSTEM_PATHS = [
  "/etc/shadow",
  "/etc/gshadow",
  "/etc/sudoers",
  "/root",
  "/proc",
  "/sys",
];


/**
 * Check whether a requested path targets a protected
 * operating-system resource.
 */
function isSensitiveSystemPath(
  resourcePath?: string
): boolean {

  if (!resourcePath) {
    return false;
  }


  const resolvedPath =
    path.resolve(resourcePath);


  return SENSITIVE_SYSTEM_PATHS.some(
    (sensitivePath) => {

      return (
        resolvedPath === sensitivePath ||
        resolvedPath.startsWith(
          sensitivePath + path.sep
        )
      );
    }
  );
}


/* =========================================================
 * 8. Workspace Boundary Protection
 * ======================================================= */

/**
 * Ensure a requested file remains inside the Agent's
 * assigned workspace.
 *
 * Prevents path traversal such as:
 *
 * ../../../etc/shadow
 */
function isInsideWorkspace(
  resourcePath: string,
  workspaceRoot: string
): boolean {

  const resolvedWorkspace =
    path.resolve(workspaceRoot);


  const resolvedTarget =
    path.isAbsolute(resourcePath)

      ? path.resolve(resourcePath)

      : path.resolve(
          resolvedWorkspace,
          resourcePath
        );


  const relativePath =
    path.relative(
      resolvedWorkspace,
      resolvedTarget
    );


  return (
    relativePath === "" ||
    (
      !relativePath.startsWith("..") &&
      !path.isAbsolute(relativePath)
    )
  );
}


/* =========================================================
 * 9. Result Helper
 * ======================================================= */

function createResult(
  request: AuthorizationRequest,
  decision: AuthorizationDecision,
  reason: string
): AuthorizationResult {

  const identity =
    request.identity;


  return {

    decision,

    reason,

    userId:
      identity.userId,

    agentId:
      identity.agentId,

    role:
      identity.role,

    workspaceId:
      identity.workspaceId,

    runId:
      identity.runId,

    action:
      request.action,

    resource:
      request.resource,

    timestamp:
      new Date().toISOString(),
  };
}


/* =========================================================
 * 10. Authorization Policy Engine
 * ======================================================= */

async function evaluatePolicy(
  request: AuthorizationRequest,
  workspaceRoot: string,
  deps: AuthorizationDependencies
): Promise<AuthorizationResult> {

  const identity =
    request.identity;


  /* -------------------------------------------------------
   * Rule 1:
   * Sensitive system resources are always denied.
   * ----------------------------------------------------- */

  if (
    isSensitiveSystemPath(
      request.resource.path
    )
  ) {

    return createResult(
      request,
      "DENY",
      "Access to sensitive system resources is forbidden."
    );
  }


  /* -------------------------------------------------------
   * Rule 2:
   * Planner cannot execute shell commands.
   * ----------------------------------------------------- */

  if (
    identity.role === "PLANNER" &&
    request.action === "SHELL_EXECUTE"
  ) {

    return createResult(
      request,
      "DENY",
      "Planner agents are not allowed to execute shell commands."
    );
  }


  /* -------------------------------------------------------
   * Rule 3:
   * Reviewer cannot execute shell commands.
   * ----------------------------------------------------- */

  if (
    identity.role === "REVIEWER" &&
    request.action === "SHELL_EXECUTE"
  ) {

    return createResult(
      request,
      "DENY",
      "Reviewer agents are not allowed to execute shell commands."
    );
  }


  /* -------------------------------------------------------
   * Rule 4:
   * Direct secret access is always denied.
   * ----------------------------------------------------- */

  if (
    request.action === "SECRET_READ"
  ) {

    return createResult(
      request,
      "DENY",
      "Direct secret access is not permitted."
    );
  }


  /* -------------------------------------------------------
   * Rule 5:
   * High-risk operations require human approval.
   * ----------------------------------------------------- */

  if (
    request.resource.risk === "HIGH"
  ) {

    const approvalId =
      request.resource.approvalId;


    if (
      approvalId &&
      deps.isApprovalGranted
    ) {

      const approved =
        await deps.isApprovalGranted(
          approvalId,
          request
        );


      if (approved) {

        return createResult(
          request,
          "ALLOW",
          "High-risk operation has been approved by a human."
        );
      }
    }


    return createResult(
      request,
      "REQUIRE_APPROVAL",
      "High-risk operation requires human approval."
    );
  }


  /* -------------------------------------------------------
   * Rule 6:
   * FILE_WRITE
   *
   * Only Executor can write files.
   * File must remain inside assigned workspace.
   * ----------------------------------------------------- */

  if (
    request.action === "FILE_WRITE"
  ) {

    if (
      identity.role !== "EXECUTOR"
    ) {

      return createResult(
        request,
        "DENY",
        "Only Executor agents are allowed to write files."
      );
    }


    if (
      !request.resource.path
    ) {

      return createResult(
        request,
        "DENY",
        "FILE_WRITE requires a resource path."
      );
    }


    if (
      !isInsideWorkspace(
        request.resource.path,
        workspaceRoot
      )
    ) {

      return createResult(
        request,
        "DENY",
        "Agent cannot write files outside its assigned workspace."
      );
    }


    return createResult(
      request,
      "ALLOW",
      "Executor may write files inside its assigned workspace."
    );
  }


  /* -------------------------------------------------------
   * Rule 7:
   * FILE_READ
   *
   * Agent can read only inside its assigned workspace.
   * ----------------------------------------------------- */

  if (
    request.action === "FILE_READ"
  ) {

    if (
      !request.resource.path
    ) {

      return createResult(
        request,
        "DENY",
        "FILE_READ requires a resource path."
      );
    }


    if (
      !isInsideWorkspace(
        request.resource.path,
        workspaceRoot
      )
    ) {

      return createResult(
        request,
        "DENY",
        "Agent cannot read files outside its assigned workspace."
      );
    }


    return createResult(
      request,
      "ALLOW",
      "Agent may read files inside its assigned workspace."
    );
  }


  /* -------------------------------------------------------
   * Rule 8:
   * SHELL_EXECUTE
   *
   * Only Executor can execute shell commands.
   * ----------------------------------------------------- */

  if (
    request.action === "SHELL_EXECUTE"
  ) {

    if (
      identity.role === "EXECUTOR"
    ) {

      return createResult(
        request,
        "ALLOW",
        "Executor role is allowed to execute shell commands."
      );
    }


    return createResult(
      request,
      "DENY",
      "Agent role is not allowed to execute shell commands."
    );
  }


  /* -------------------------------------------------------
   * Rule 9:
   * TOOL_INVOKE
   *
   * Executor and Orchestrator may invoke normal tools.
   * ----------------------------------------------------- */

  if (
    request.action === "TOOL_INVOKE"
  ) {

    if (
      identity.role === "EXECUTOR" ||
      identity.role === "ORCHESTRATOR"
    ) {

      return createResult(
        request,
        "ALLOW",
        "Agent role is allowed to invoke this tool."
      );
    }


    return createResult(
      request,
      "DENY",
      "Agent role is not allowed to invoke tools."
    );
  }


  /* -------------------------------------------------------
   * Rule 10:
   * NETWORK_REQUEST
   *
   * Executor and Orchestrator may perform normal network
   * requests.
   * ----------------------------------------------------- */

  if (
    request.action === "NETWORK_REQUEST"
  ) {

    if (
      identity.role === "EXECUTOR" ||
      identity.role === "ORCHESTRATOR"
    ) {

      return createResult(
        request,
        "ALLOW",
        "Agent role is allowed to perform this network request."
      );
    }


    return createResult(
      request,
      "DENY",
      "Agent role is not allowed to perform network requests."
    );
  }


  /* -------------------------------------------------------
   * Rule 11:
   * Deny by default.
   * ----------------------------------------------------- */

  return createResult(
    request,
    "DENY",
    "No authorization policy allows this action."
  );
}


/* =========================================================
 * 11. Main Authorization Function
 * ======================================================= */

export async function authorize(
  request: AuthorizationRequest,
  deps: AuthorizationDependencies
): Promise<AuthorizationResult> {

  /*
   * Defense-in-depth:
   *
   * resolveAgentIdentity() should already guarantee these
   * values exist.
   */
  if (
    !request.identity.userId ||
    !request.identity.agentId ||
    !request.identity.role ||
    !request.identity.workspaceId ||
    !request.identity.runId
  ) {

    const result =
      createResult(
        request,
        "DENY",
        "Incomplete Agent identity."
      );


    await deps.writeAuditLog(
      result
    );


    return result;
  }


  /*
   * Resolve workspace root using trusted workspaceId.
   */
  let workspaceRoot: string;


  try {

    workspaceRoot =
      await deps.resolveWorkspaceRoot(
        request.identity.workspaceId
      );

  } catch {

    const result =
      createResult(
        request,
        "DENY",
        "Assigned workspace could not be resolved."
      );


    await deps.writeAuditLog(
      result
    );


    return result;
  }


  /*
   * Evaluate policies.
   */
  const result =
    await evaluatePolicy(
      request,
      workspaceRoot,
      deps
    );


  /*
   * Record every authorization decision.
   */
  await deps.writeAuditLog(
    result
  );


  return result;
}


/* =========================================================
 * 12. Authorization Errors
 * ======================================================= */

export class AuthorizationDeniedError
  extends Error {

  public readonly statusCode = 403;

  public readonly decision =
    "DENY" as const;


  constructor(
    public readonly authorization:
      AuthorizationResult
  ) {

    super(
      authorization.reason
    );


    this.name =
      "AuthorizationDeniedError";
  }
}


export class ApprovalRequiredError
  extends Error {

  public readonly statusCode = 409;

  public readonly decision =
    "REQUIRE_APPROVAL" as const;


  constructor(
    public readonly authorization:
      AuthorizationResult
  ) {

    super(
      authorization.reason
    );


    this.name =
      "ApprovalRequiredError";
  }
}


/* =========================================================
 * 13. Runtime Protection
 * ======================================================= */

/**
 * Only an ALLOW decision can execute runtimeAction().
 *
 * DENY and REQUIRE_APPROVAL stop before runtime execution.
 */
export async function executeProtectedAction<T>(
  request: AuthorizationRequest,
  deps: AuthorizationDependencies,
  runtimeAction: () => Promise<T>
): Promise<T> {

  const result =
    await authorize(
      request,
      deps
    );


  if (
    result.decision === "DENY"
  ) {

    throw new AuthorizationDeniedError(
      result
    );
  }


  if (
    result.decision ===
    "REQUIRE_APPROVAL"
  ) {

    throw new ApprovalRequiredError(
      result
    );
  }


  /*
   * Only ALLOW reaches this line.
   */
  return runtimeAction();
}